//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retromind.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Retromind.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CtxAddCategory {
            get {
                return ResourceManager.GetString("CtxAddCategory", resourceCulture);
            }
        }
        
        public static string CtxAddMedia {
            get {
                return ResourceManager.GetString("CtxAddMedia", resourceCulture);
            }
        }
        
        public static string CtxDelete {
            get {
                return ResourceManager.GetString("CtxDelete", resourceCulture);
            }
        }
        
        public static string MsgEnterName {
            get {
                return ResourceManager.GetString("MsgEnterName", resourceCulture);
            }
        }
        
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string LaunchConfig {
            get {
                return ResourceManager.GetString("LaunchConfig", resourceCulture);
            }
        }
        
        public static string LauncherPath {
            get {
                return ResourceManager.GetString("LauncherPath", resourceCulture);
            }
        }
        
        public static string LauncherPathHint {
            get {
                return ResourceManager.GetString("LauncherPathHint", resourceCulture);
            }
        }
        
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        public static string ArgumentsHint {
            get {
                return ResourceManager.GetString("ArgumentsHint", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string EditMediaTitle {
            get {
                return ResourceManager.GetString("EditMediaTitle", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteNode {
            get {
                return ResourceManager.GetString("ConfirmDeleteNode", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteMedia {
            get {
                return ResourceManager.GetString("ConfirmDeleteMedia", resourceCulture);
            }
        }
        
        public static string SelectMediaFile {
            get {
                return ResourceManager.GetString("SelectMediaFile", resourceCulture);
            }
        }
        
        public static string SelectCover {
            get {
                return ResourceManager.GetString("SelectCover", resourceCulture);
            }
        }
        
        public static string SelectLogo {
            get {
                return ResourceManager.GetString("SelectLogo", resourceCulture);
            }
        }
        
        public static string SelectWallpaper {
            get {
                return ResourceManager.GetString("SelectWallpaper", resourceCulture);
            }
        }
        
        public static string SelectMusic {
            get {
                return ResourceManager.GetString("SelectMusic", resourceCulture);
            }
        }
        
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        public static string CtxChangeCover {
            get {
                return ResourceManager.GetString("CtxChangeCover", resourceCulture);
            }
        }
        
        public static string CtxChangeLogo {
            get {
                return ResourceManager.GetString("CtxChangeLogo", resourceCulture);
            }
        }
        
        public static string CtxChangeWallpaper {
            get {
                return ResourceManager.GetString("CtxChangeWallpaper", resourceCulture);
            }
        }
        
        public static string CtxChangeMusic {
            get {
                return ResourceManager.GetString("CtxChangeMusic", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        public static string LastPlayed {
            get {
                return ResourceManager.GetString("LastPlayed", resourceCulture);
            }
        }
        
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        public static string LaunchMode {
            get {
                return ResourceManager.GetString("LaunchMode", resourceCulture);
            }
        }
        
        public static string ModeNative {
            get {
                return ResourceManager.GetString("ModeNative", resourceCulture);
            }
        }
        
        public static string ModeEmulator {
            get {
                return ResourceManager.GetString("ModeEmulator", resourceCulture);
            }
        }
        
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string SectionEmulators {
            get {
                return ResourceManager.GetString("SectionEmulators", resourceCulture);
            }
        }
        
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        public static string ExecutablePath {
            get {
                return ResourceManager.GetString("ExecutablePath", resourceCulture);
            }
        }
        
        public static string DefaultArguments {
            get {
                return ResourceManager.GetString("DefaultArguments", resourceCulture);
            }
        }
        
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        public static string GlobalSettingsHint {
            get {
                return ResourceManager.GetString("GlobalSettingsHint", resourceCulture);
            }
        }
        
        public static string TabEmulators {
            get {
                return ResourceManager.GetString("TabEmulators", resourceCulture);
            }
        }
        
        public static string TabMetadata {
            get {
                return ResourceManager.GetString("TabMetadata", resourceCulture);
            }
        }
        
        public static string NewScraperDefaultName {
            get {
                return ResourceManager.GetString("NewScraperDefaultName", resourceCulture);
            }
        }
        
        public static string HintTmdbKey {
            get {
                return ResourceManager.GetString("HintTmdbKey", resourceCulture);
            }
        }
        
        public static string HintIgdbCredentials {
            get {
                return ResourceManager.GetString("HintIgdbCredentials", resourceCulture);
            }
        }
        
        public static string HintRequired {
            get {
                return ResourceManager.GetString("HintRequired", resourceCulture);
            }
        }
        
        public static string AutomaticMetadataSearch {
            get {
                return ResourceManager.GetString("AutomaticMetadataSearch", resourceCulture);
            }
        }
        
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string ProcessMonitor {
            get {
                return ResourceManager.GetString("ProcessMonitor", resourceCulture);
            }
        }
        
        public static string TimePlayedHint {
            get {
                return ResourceManager.GetString("TimePlayedHint", resourceCulture);
            }
        }
        
        public static string WatermarkOverrideWatchProcess {
            get {
                return ResourceManager.GetString("WatermarkOverrideWatchProcess", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        public static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
        
        public static string MusicFiles {
            get {
                return ResourceManager.GetString("MusicFiles", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string SetMusicActive {
            get {
                return ResourceManager.GetString("SetMusicActive", resourceCulture);
            }
        }
        
        public static string AddMusic {
            get {
                return ResourceManager.GetString("AddMusic", resourceCulture);
            }
        }
        
        public static string ToggleTheme {
            get {
                return ResourceManager.GetString("ToggleTheme", resourceCulture);
            }
        }
        
        public static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        public static string ImportRoms {
            get {
                return ResourceManager.GetString("ImportRoms", resourceCulture);
            }
        }
        
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        public static string ImportSteam {
            get {
                return ResourceManager.GetString("ImportSteam", resourceCulture);
            }
        }
        
        public static string SearchMetadataAll {
            get {
                return ResourceManager.GetString("SearchMetadataAll", resourceCulture);
            }
        }
        
        public static string ImportGog {
            get {
                return ResourceManager.GetString("ImportGog", resourceCulture);
            }
        }
        
        public static string MediaSettings {
            get {
                return ResourceManager.GetString("MediaSettings", resourceCulture);
            }
        }
        
        public static string ChooseMedia {
            get {
                return ResourceManager.GetString("ChooseMedia", resourceCulture);
            }
        }
        
        public static string TipRandomGame {
            get {
                return ResourceManager.GetString("TipRandomGame", resourceCulture);
            }
        }
        
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string ImportFolder {
            get {
                return ResourceManager.GetString("ImportFolder", resourceCulture);
            }
        }
        
        public static string LoadMetadata {
            get {
                return ResourceManager.GetString("LoadMetadata", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        public static string RandomCover {
            get {
                return ResourceManager.GetString("RandomCover", resourceCulture);
            }
        }
        
        public static string TipRandomImage {
            get {
                return ResourceManager.GetString("TipRandomImage", resourceCulture);
            }
        }
        
        public static string RandomMusic {
            get {
                return ResourceManager.GetString("RandomMusic", resourceCulture);
            }
        }
        
        public static string TipRandomMusic {
            get {
                return ResourceManager.GetString("TipRandomMusic", resourceCulture);
            }
        }
        
        public static string StandardEmulator {
            get {
                return ResourceManager.GetString("StandardEmulator", resourceCulture);
            }
        }
        
        public static string EmulatorSelection {
            get {
                return ResourceManager.GetString("EmulatorSelection", resourceCulture);
            }
        }
        
        public static string ChooseSource {
            get {
                return ResourceManager.GetString("ChooseSource", resourceCulture);
            }
        }
        
        public static string SearchMetadata {
            get {
                return ResourceManager.GetString("SearchMetadata", resourceCulture);
            }
        }
        
        public static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        public static string PreviewShort {
            get {
                return ResourceManager.GetString("PreviewShort", resourceCulture);
            }
        }
        
        public static string CoverURL {
            get {
                return ResourceManager.GetString("CoverURL", resourceCulture);
            }
        }
        
        public static string TitleEx {
            get {
                return ResourceManager.GetString("TitleEx", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        public static string SearchProceeds {
            get {
                return ResourceManager.GetString("SearchProceeds", resourceCulture);
            }
        }
        
        public static string TakeOver {
            get {
                return ResourceManager.GetString("TakeOver", resourceCulture);
            }
        }
        
        public static string GlobalSearchShort {
            get {
                return ResourceManager.GetString("GlobalSearchShort", resourceCulture);
            }
        }
        
        public static string TitleSearch {
            get {
                return ResourceManager.GetString("TitleSearch", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        public static string RandomMatch {
            get {
                return ResourceManager.GetString("RandomMatch", resourceCulture);
            }
        }
        
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        public static string ConfigureMetadata {
            get {
                return ResourceManager.GetString("ConfigureMetadata", resourceCulture);
            }
        }
        
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string AccessData {
            get {
                return ResourceManager.GetString("AccessData", resourceCulture);
            }
        }
        
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        public static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string DataLanguage {
            get {
                return ResourceManager.GetString("DataLanguage", resourceCulture);
            }
        }
        
        public static string ChooseASource {
            get {
                return ResourceManager.GetString("ChooseASource", resourceCulture);
            }
        }
        
        public static string ScrapeArea {
            get {
                return ResourceManager.GetString("ScrapeArea", resourceCulture);
            }
        }
    }
}
