//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retromind.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Retromind.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button.Edit", resourceCulture);
            }
        }
        
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button.Import", resourceCulture);
            }
        }
        
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button.Ok", resourceCulture);
            }
        }
        
        public static string Button_Play {
            get {
                return ResourceManager.GetString("Button.Play", resourceCulture);
            }
        }
        
        public static string Button_Random {
            get {
                return ResourceManager.GetString("Button.Random", resourceCulture);
            }
        }
        
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        public static string Button_TakeOver {
            get {
                return ResourceManager.GetString("Button.TakeOver", resourceCulture);
            }
        }
        
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button.No", resourceCulture);
            }
        }
        
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button.Yes", resourceCulture);
            }
        }
        
        public static string Button_Cover {
            get {
                return ResourceManager.GetString("Button.Cover", resourceCulture);
            }
        }
        
        public static string Button_Logo {
            get {
                return ResourceManager.GetString("Button.Logo", resourceCulture);
            }
        }
        
        public static string Button_Wall {
            get {
                return ResourceManager.GetString("Button.Wall", resourceCulture);
            }
        }
        
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button.Delete", resourceCulture);
            }
        }
        
        public static string Button_Launch {
            get {
                return ResourceManager.GetString("Button.Launch", resourceCulture);
            }
        }
        
        public static string Common_Active {
            get {
                return ResourceManager.GetString("Common.Active", resourceCulture);
            }
        }
        
        public static string Common_Area {
            get {
                return ResourceManager.GetString("Common.Area", resourceCulture);
            }
        }
        
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common.Description", resourceCulture);
            }
        }
        
        public static string Common_Developer {
            get {
                return ResourceManager.GetString("Common.Developer", resourceCulture);
            }
        }
        
        public static string Common_Genre {
            get {
                return ResourceManager.GetString("Common.Genre", resourceCulture);
            }
        }
        
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common.Name", resourceCulture);
            }
        }
        
        public static string Common_Options {
            get {
                return ResourceManager.GetString("Common.Options", resourceCulture);
            }
        }
        
        public static string Common_PreviewShort {
            get {
                return ResourceManager.GetString("Common.PreviewShort", resourceCulture);
            }
        }
        
        public static string Common_Rating {
            get {
                return ResourceManager.GetString("Common.Rating", resourceCulture);
            }
        }
        
        public static string Common_ReleaseDate {
            get {
                return ResourceManager.GetString("Common.ReleaseDate", resourceCulture);
            }
        }
        
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common.Status", resourceCulture);
            }
        }
        
        public static string Common_Summary {
            get {
                return ResourceManager.GetString("Common.Summary", resourceCulture);
            }
        }
        
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common.Title", resourceCulture);
            }
        }
        
        public static string Common_Year {
            get {
                return ResourceManager.GetString("Common.Year", resourceCulture);
            }
        }
        
        public static string Common_CoverURL {
            get {
                return ResourceManager.GetString("Common.CoverURL", resourceCulture);
            }
        }
        
        public static string Common_TitleEx {
            get {
                return ResourceManager.GetString("Common.TitleEx", resourceCulture);
            }
        }
        
        public static string Common_UserName {
            get {
                return ResourceManager.GetString("Common.UserName", resourceCulture);
            }
        }
        
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common.Password", resourceCulture);
            }
        }
        
        public static string Ctx_Category_Add {
            get {
                return ResourceManager.GetString("Ctx.Category.Add", resourceCulture);
            }
        }
        
        public static string Ctx_ImportRoms {
            get {
                return ResourceManager.GetString("Ctx.ImportRoms", resourceCulture);
            }
        }
        
        public static string Ctx_Media_Add {
            get {
                return ResourceManager.GetString("Ctx.Media.Add", resourceCulture);
            }
        }
        
        public static string Ctx_ChangeCover {
            get {
                return ResourceManager.GetString("Ctx.ChangeCover", resourceCulture);
            }
        }
        
        public static string Dialog_ChooseASource {
            get {
                return ResourceManager.GetString("Dialog.ChooseASource", resourceCulture);
            }
        }
        
        public static string Dialog_ChooseMedia {
            get {
                return ResourceManager.GetString("Dialog.ChooseMedia", resourceCulture);
            }
        }
        
        public static string Dialog_ChooseSource {
            get {
                return ResourceManager.GetString("Dialog.ChooseSource", resourceCulture);
            }
        }
        
        public static string Dialog_ConfigureMetadata {
            get {
                return ResourceManager.GetString("Dialog.ConfigureMetadata", resourceCulture);
            }
        }
        
        public static string Dialog_EditMedia {
            get {
                return ResourceManager.GetString("Dialog.EditMedia", resourceCulture);
            }
        }
        
        public static string Dialog_EnterName_Message {
            get {
                return ResourceManager.GetString("Dialog.EnterName.Message", resourceCulture);
            }
        }
        
        public static string Dialog_LoadMetadata {
            get {
                return ResourceManager.GetString("Dialog.LoadMetadata", resourceCulture);
            }
        }
        
        public static string Dialog_MsgConfirmDelete {
            get {
                return ResourceManager.GetString("Dialog.MsgConfirmDelete", resourceCulture);
            }
        }
        
        public static string Dialog_NoResult {
            get {
                return ResourceManager.GetString("Dialog.NoResult", resourceCulture);
            }
        }
        
        public static string Dialog_SearchTerm {
            get {
                return ResourceManager.GetString("Dialog.SearchTerm", resourceCulture);
            }
        }
        
        public static string Dialog_Select_Cover {
            get {
                return ResourceManager.GetString("Dialog.Select.Cover", resourceCulture);
            }
        }
        
        public static string Dialog_Select_Logo {
            get {
                return ResourceManager.GetString("Dialog.Select.Logo", resourceCulture);
            }
        }
        
        public static string Dialog_Select_Music {
            get {
                return ResourceManager.GetString("Dialog.Select.Music", resourceCulture);
            }
        }
        
        public static string Dialog_Select_Wallpaper {
            get {
                return ResourceManager.GetString("Dialog.Select.Wallpaper", resourceCulture);
            }
        }
        
        public static string Dialog_TitleSearch {
            get {
                return ResourceManager.GetString("Dialog.TitleSearch", resourceCulture);
            }
        }
        
        public static string Hint_IgdbCredentials {
            get {
                return ResourceManager.GetString("Hint.IgdbCredentials", resourceCulture);
            }
        }
        
        public static string Hint_Required {
            get {
                return ResourceManager.GetString("Hint.Required", resourceCulture);
            }
        }
        
        public static string Hint_TimePlayed {
            get {
                return ResourceManager.GetString("Hint.TimePlayed", resourceCulture);
            }
        }
        
        public static string Hint_TmdbKey {
            get {
                return ResourceManager.GetString("Hint.TmdbKey", resourceCulture);
            }
        }
        
        public static string Import_Folder {
            get {
                return ResourceManager.GetString("Import.Folder", resourceCulture);
            }
        }
        
        public static string Import_Gog {
            get {
                return ResourceManager.GetString("Import.Gog", resourceCulture);
            }
        }
        
        public static string Import_Roms {
            get {
                return ResourceManager.GetString("Import.Roms", resourceCulture);
            }
        }
        
        public static string Import_Steam {
            get {
                return ResourceManager.GetString("Import.Steam", resourceCulture);
            }
        }
        
        public static string Launch_Arguments {
            get {
                return ResourceManager.GetString("Launch.Arguments", resourceCulture);
            }
        }
        
        public static string Launch_ArgumentsHint {
            get {
                return ResourceManager.GetString("Launch.ArgumentsHint", resourceCulture);
            }
        }
        
        public static string Launch_Config {
            get {
                return ResourceManager.GetString("Launch.Config", resourceCulture);
            }
        }
        
        public static string Launch_LauncherPath {
            get {
                return ResourceManager.GetString("Launch.LauncherPath", resourceCulture);
            }
        }
        
        public static string Launch_LauncherPathHint {
            get {
                return ResourceManager.GetString("Launch.LauncherPathHint", resourceCulture);
            }
        }
        
        public static string Launch_Mode {
            get {
                return ResourceManager.GetString("Launch.Mode", resourceCulture);
            }
        }
        
        public static string Media_AddMusic {
            get {
                return ResourceManager.GetString("Media.AddMusic", resourceCulture);
            }
        }
        
        public static string Media_EmulatorSelection {
            get {
                return ResourceManager.GetString("Media.EmulatorSelection", resourceCulture);
            }
        }
        
        public static string Media_LastPlayed {
            get {
                return ResourceManager.GetString("Media.LastPlayed", resourceCulture);
            }
        }
        
        public static string Media_Library {
            get {
                return ResourceManager.GetString("Media.Library", resourceCulture);
            }
        }
        
        public static string Media_MusicFiles {
            get {
                return ResourceManager.GetString("Media.MusicFiles", resourceCulture);
            }
        }
        
        public static string Media_PlayCount {
            get {
                return ResourceManager.GetString("Media.PlayCount", resourceCulture);
            }
        }
        
        public static string Media_RandomCover {
            get {
                return ResourceManager.GetString("Media.RandomCover", resourceCulture);
            }
        }
        
        public static string Media_RandomMusic {
            get {
                return ResourceManager.GetString("Media.RandomMusic", resourceCulture);
            }
        }
        
        public static string Media_SetMusicActive {
            get {
                return ResourceManager.GetString("Media.SetMusicActive", resourceCulture);
            }
        }
        
        public static string Media_Settings {
            get {
                return ResourceManager.GetString("Media.Settings", resourceCulture);
            }
        }
        
        public static string Media_StandardEmulator {
            get {
                return ResourceManager.GetString("Media.StandardEmulator", resourceCulture);
            }
        }
        
        public static string Media_WatermarkOverrideWatchProcess {
            get {
                return ResourceManager.GetString("Media.WatermarkOverrideWatchProcess", resourceCulture);
            }
        }
        
        public static string Metadata_AccessData {
            get {
                return ResourceManager.GetString("Metadata.AccessData", resourceCulture);
            }
        }
        
        public static string Metadata_ApiKey {
            get {
                return ResourceManager.GetString("Metadata.ApiKey", resourceCulture);
            }
        }
        
        public static string Metadata_AutomaticSearch {
            get {
                return ResourceManager.GetString("Metadata.AutomaticSearch", resourceCulture);
            }
        }
        
        public static string Metadata_Client {
            get {
                return ResourceManager.GetString("Metadata.Client", resourceCulture);
            }
        }
        
        public static string Metadata_ClientSecret {
            get {
                return ResourceManager.GetString("Metadata.ClientSecret", resourceCulture);
            }
        }
        
        public static string Metadata_DataLanguage {
            get {
                return ResourceManager.GetString("Metadata.DataLanguage", resourceCulture);
            }
        }
        
        public static string Metadata_Designation {
            get {
                return ResourceManager.GetString("Metadata.Designation", resourceCulture);
            }
        }
        
        public static string Metadata_NewScraper {
            get {
                return ResourceManager.GetString("Metadata.NewScraper", resourceCulture);
            }
        }
        
        public static string Metadata_ScrapeArea {
            get {
                return ResourceManager.GetString("Metadata.ScrapeArea", resourceCulture);
            }
        }
        
        public static string Metadata_SearchMetadata {
            get {
                return ResourceManager.GetString("Metadata.SearchMetadata", resourceCulture);
            }
        }
        
        public static string Metadata_SearchMetadataAll {
            get {
                return ResourceManager.GetString("Metadata.SearchMetadataAll", resourceCulture);
            }
        }
        
        public static string Metadata_Search_InProgress {
            get {
                return ResourceManager.GetString("Metadata.Search.InProgress", resourceCulture);
            }
        }
        
        public static string Metadata_Source {
            get {
                return ResourceManager.GetString("Metadata.Source", resourceCulture);
            }
        }
        
        public static string Metadata_Type {
            get {
                return ResourceManager.GetString("Metadata.Type", resourceCulture);
            }
        }
        
        public static string Profile_New {
            get {
                return ResourceManager.GetString("Profile.New", resourceCulture);
            }
        }
        
        public static string Profile_Profile {
            get {
                return ResourceManager.GetString("Profile.Profile", resourceCulture);
            }
        }
        
        public static string Process_Monitor {
            get {
                return ResourceManager.GetString("Process.Monitor", resourceCulture);
            }
        }
        
        public static string RandomMatch_Start {
            get {
                return ResourceManager.GetString("RandomMatch.Start", resourceCulture);
            }
        }
        
        public static string Search_Global {
            get {
                return ResourceManager.GetString("Search.Global", resourceCulture);
            }
        }
        
        public static string Search_GlobalShort {
            get {
                return ResourceManager.GetString("Search.GlobalShort", resourceCulture);
            }
        }
        
        public static string Search_Search {
            get {
                return ResourceManager.GetString("Search.Search", resourceCulture);
            }
        }
        
        public static string Settings_AddProfile {
            get {
                return ResourceManager.GetString("Settings.AddProfile", resourceCulture);
            }
        }
        
        public static string Settings_DefaultArguments {
            get {
                return ResourceManager.GetString("Settings.DefaultArguments", resourceCulture);
            }
        }
        
        public static string Settings_ExecutablePath {
            get {
                return ResourceManager.GetString("Settings.ExecutablePath", resourceCulture);
            }
        }
        
        public static string Settings_GlobalSettingsHint {
            get {
                return ResourceManager.GetString("Settings.GlobalSettingsHint", resourceCulture);
            }
        }
        
        public static string Settings_ProfileName {
            get {
                return ResourceManager.GetString("Settings.ProfileName", resourceCulture);
            }
        }
        
        public static string Settings_SectionEmulators {
            get {
                return ResourceManager.GetString("Settings.SectionEmulators", resourceCulture);
            }
        }
        
        public static string Settings_TabEmulators {
            get {
                return ResourceManager.GetString("Settings.TabEmulators", resourceCulture);
            }
        }
        
        public static string Settings_TabMetadata {
            get {
                return ResourceManager.GetString("Settings.TabMetadata", resourceCulture);
            }
        }
        
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        public static string Toggle_Theme {
            get {
                return ResourceManager.GetString("Toggle.Theme", resourceCulture);
            }
        }
        
        public static string TimePlayed_Never {
            get {
                return ResourceManager.GetString("TimePlayed.Never", resourceCulture);
            }
        }
        
        public static string Tip_RandomGame {
            get {
                return ResourceManager.GetString("Tip.RandomGame", resourceCulture);
            }
        }
        
        public static string Tip_RandomImage {
            get {
                return ResourceManager.GetString("Tip.RandomImage", resourceCulture);
            }
        }
        
        public static string Tip_RandomMusic {
            get {
                return ResourceManager.GetString("Tip.RandomMusic", resourceCulture);
            }
        }
        
        public static string Type_Command {
            get {
                return ResourceManager.GetString("Type.Command", resourceCulture);
            }
        }
        
        public static string Type_Emulator {
            get {
                return ResourceManager.GetString("Type.Emulator", resourceCulture);
            }
        }
        
        public static string Type_Native {
            get {
                return ResourceManager.GetString("Type.Native", resourceCulture);
            }
        }
        
        public static string Zoom_Zoom {
            get {
                return ResourceManager.GetString("Zoom.Zoom", resourceCulture);
            }
        }
        
        public static string Media_PlayTime {
            get {
                return ResourceManager.GetString("Media.PlayTime", resourceCulture);
            }
        }
    }
}
