//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retromind.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Retromind.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CtxAddCategory {
            get {
                return ResourceManager.GetString("CtxAddCategory", resourceCulture);
            }
        }
        
        public static string CtxAddMedia {
            get {
                return ResourceManager.GetString("CtxAddMedia", resourceCulture);
            }
        }
        
        public static string CtxDelete {
            get {
                return ResourceManager.GetString("CtxDelete", resourceCulture);
            }
        }
        
        public static string MsgEnterName {
            get {
                return ResourceManager.GetString("MsgEnterName", resourceCulture);
            }
        }
        
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string LaunchConfig {
            get {
                return ResourceManager.GetString("LaunchConfig", resourceCulture);
            }
        }
        
        public static string LauncherPath {
            get {
                return ResourceManager.GetString("LauncherPath", resourceCulture);
            }
        }
        
        public static string LauncherPathHint {
            get {
                return ResourceManager.GetString("LauncherPathHint", resourceCulture);
            }
        }
        
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        public static string ArgumentsHint {
            get {
                return ResourceManager.GetString("ArgumentsHint", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string EditMediaTitle {
            get {
                return ResourceManager.GetString("EditMediaTitle", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteNode {
            get {
                return ResourceManager.GetString("ConfirmDeleteNode", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteMedia {
            get {
                return ResourceManager.GetString("ConfirmDeleteMedia", resourceCulture);
            }
        }
        
        public static string SelectMediaFile {
            get {
                return ResourceManager.GetString("SelectMediaFile", resourceCulture);
            }
        }
        
        public static string SelectCover {
            get {
                return ResourceManager.GetString("SelectCover", resourceCulture);
            }
        }
        
        public static string SelectLogo {
            get {
                return ResourceManager.GetString("SelectLogo", resourceCulture);
            }
        }
        
        public static string SelectWallpaper {
            get {
                return ResourceManager.GetString("SelectWallpaper", resourceCulture);
            }
        }
        
        public static string SelectMusic {
            get {
                return ResourceManager.GetString("SelectMusic", resourceCulture);
            }
        }
        
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        public static string CtxChangeCover {
            get {
                return ResourceManager.GetString("CtxChangeCover", resourceCulture);
            }
        }
        
        public static string CtxChangeLogo {
            get {
                return ResourceManager.GetString("CtxChangeLogo", resourceCulture);
            }
        }
        
        public static string CtxChangeWallpaper {
            get {
                return ResourceManager.GetString("CtxChangeWallpaper", resourceCulture);
            }
        }
        
        public static string CtxChangeMusic {
            get {
                return ResourceManager.GetString("CtxChangeMusic", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        public static string LastPlayed {
            get {
                return ResourceManager.GetString("LastPlayed", resourceCulture);
            }
        }
        
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        public static string LaunchMode {
            get {
                return ResourceManager.GetString("LaunchMode", resourceCulture);
            }
        }
        
        public static string ModeNative {
            get {
                return ResourceManager.GetString("ModeNative", resourceCulture);
            }
        }
        
        public static string ModeEmulator {
            get {
                return ResourceManager.GetString("ModeEmulator", resourceCulture);
            }
        }
        
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string SectionEmulators {
            get {
                return ResourceManager.GetString("SectionEmulators", resourceCulture);
            }
        }
        
        public static string AddProfile {
            get {
                return ResourceManager.GetString("AddProfile", resourceCulture);
            }
        }
        
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        public static string ExecutablePath {
            get {
                return ResourceManager.GetString("ExecutablePath", resourceCulture);
            }
        }
        
        public static string DefaultArguments {
            get {
                return ResourceManager.GetString("DefaultArguments", resourceCulture);
            }
        }
        
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        public static string GlobalSettingsHint {
            get {
                return ResourceManager.GetString("GlobalSettingsHint", resourceCulture);
            }
        }
        
        public static string TabEmulators {
            get {
                return ResourceManager.GetString("TabEmulators", resourceCulture);
            }
        }
        
        public static string TabMetadata {
            get {
                return ResourceManager.GetString("TabMetadata", resourceCulture);
            }
        }
        
        public static string NewScraperDefaultName {
            get {
                return ResourceManager.GetString("NewScraperDefaultName", resourceCulture);
            }
        }
        
        public static string HintTmdbKey {
            get {
                return ResourceManager.GetString("HintTmdbKey", resourceCulture);
            }
        }
        
        public static string HintIgdbCredentials {
            get {
                return ResourceManager.GetString("HintIgdbCredentials", resourceCulture);
            }
        }
        
        public static string HintRequired {
            get {
                return ResourceManager.GetString("HintRequired", resourceCulture);
            }
        }
    }
}
